spring.application.name=springboot-demo

langchain4j.open-ai.chat-model.api-key=sk-e3e010f3d9514a73a5805bd1ad629c16
langchain4j.open-ai.chat-model.model-name=deepseek-chat
langchain4j.open-ai.chat-model.base-url=https://api.deepseek.com/v1

# 配置流式响应的 api 信息
langchain4j.open-ai.streaming-chat-model.api-key=sk-e3e010f3d9514a73a5805bd1ad629c16
langchain4j.open-ai.streaming-chat-model.model-name=deepseek-chat
langchain4j.open-ai.streaming-chat-model.base-url=https://api.deepseek.com/v1

server.port=8081